export enum Configuration {
  SHIP_COMMAND_FRIGATE = "SHIP_COMMAND_FRIGATE",
  SHIP_EXPLORER = "SHIP_EXPLORER",
  SHIP_HEAVY_FREIGHTER = "SHIP_HEAVY_FREIGHTER",
  SHIP_INTERCEPTOR = "SHIP_INTERCEPTOR",
  SHIP_LIGHT_HAULER = "SHIP_LIGHT_HAULER",
  SHIP_LIGHT_SHUTTLE = "SHIP_LIGHT_SHUTTLE",
  SHIP_MINING_DRONE = "SHIP_MINING_DRONE",
  SHIP_ORE_HOUND = "SHIP_ORE_HOUND",
  SHIP_PROBE = "SHIP_PROBE",
  SHIP_SIPHON_DRONE = "SHIP_SIPHON_DRONE",
  SHIP_SURVEYOR = "SHIP_SURVEYOR",
  SHIP_REFINING_FREIGHTER = "SHIP_REFINING_FREIGHTER",
}
